export const OPEN_PRIVACY_POLICY = 'OPEN_PRIVACY_POLICY';

export const OPEN_MODAL_DISCRIPTION = 'OPEN_MODAL_DISCRIPTION';

export const OPEN_MODAL_HELLO = 'OPEN_MODAL_HELLO';

export const CREATE_PROMPT_ARRAY = 'CREATE_PROMPT_ARRAY';

export const OPEN_REQUISITION_CARD = 'OPEN_REQUISITION_CARD';

export const OPEN_PURCHASE_REQUISITION = 'OPEN_PURCHASE_REQUISITION';

export const GET_ORDERS_FROM_SERVER = 'GET_ORDERS_FROM_SERVER';

export const SHOW_LOADER = 'SHOW_LOADER';

export const HIDE_LOADER = 'HIDE_LOADER';

export const GET_QUESTIONS_FROM_SERVER = 'GET_QUESTIONS_FROM_SERVER';

export const ADD_NEW_QUESTION = 'ADD_NEW_QUESTION';

export const ADD_NEW_ANSWER = 'ADD_NEW_ANSWER';

export const GET_ANSWERS_FROM_SERVER = 'GET_ANSWERS_FROM_SERVER';

export const CHANGE_QUESTION_STATUS = 'CHANGE_QUESTION_STATUS';
