export const OPEN_WINDOW_REGISRATION = 'OPEN_WINDOW_REGISRATION';

export const OPEN_REQUISITION_CARD = 'OPEN_REQUISITION_CARD';

export const GET_ORDERS_FROM_SERVER = 'GET_ORDERS_FROM_SERVER';

export const SHOW_LOADER = 'SHOW_LOADER';

export const HIDE_LOADER = 'HIDE_LOADER';
